### ISSUE TITLE
最NB的加载方式，往往只需要最简单的sleep

### ISSUE THREAD

**Issue by GenshinMinecraft** [Ha3MrX/DDos-Attack#109]
代码里 time.sleep(5) 真的是笑死我了
真的简单朴素

就这效率
还不如WebBenchmark

**Comment by Remelens** [comment]
花架子是这样的

**Comment by Jincheng2012** [comment]
作者多少写个假进度条也弄个随机数增加或加个好看的进度条的库啊，这不是学py第3天做得东西吗？
