### ISSUE TITLE
sh: figlet: command not found

### ISSUE THREAD

**Issue by mariothedev** [Ha3MrX/DDos-Attack#13]
This shows up after running script. Is this something we should have installed locally?

**Comment by mariothedev** [comment]
Update. I ran this on my Mac in order to get this script to run:

``
brew install figlet
``

**Comment by manexmane21** [comment]
ok

**Comment by zeus228** [comment]
It doesn't work

**Comment by Paxv28** [comment]
try my tool: https://github.com/Paxv28/Hi-Flood
