### ISSUE TITLE
Help? 

### ISSUE THREAD

**Issue by johnmelodyme** [Ha3MrX/DDos-Attack#5]
https://github.com/Ha3MrX/DDos-Attack/blob/59e06c40853e9eae7f3ef6d9dd7819d73faad306/ddos-attack.py#L33

> Traceback (most recent call last):
>   File "ipgeolocation.py", line 32, in <module>
>     from core.IpGeoLocationLib import IpGeoLocationLib
>   File "/root/IPGeoLocation/core/IpGeoLocationLib.py", line 30, in <module>
>     from core.Utils import Utils
>   File "/root/IPGeoLocation/core/Utils.py", line 33, in <module>
>     from urllib import request
> ImportError: cannot import name request

**Comment by deadfishhackers** [comment]
that is because it tracks your ip

**Comment by johnmelodyme** [comment]
Sorry , Actually I had solved . I will closed this ... My bad bro ...
