### ISSUE TITLE
Man, get this shit outta here.

### ISSUE THREAD

**Issue by OkayTrain121** [Ha3MrX/DDos-Attack#53]

**Comment by V1L3G0D** [comment]
![20211003_021310_HDR~2.jpg](https://user-images.githubusercontent.com/86334187/135744354-b0b87cf0-30a4-4a98-9ec8-631a6137a9fa.jpg)

Art.

**Comment by OkayTrain121** [comment]
Just because you are sending packet in a while he loop with possibly multiple threads, in no way implies that, it has an effect on the Rx. 
Have you measured the ping to see if the Rx is responsive? Post that art too.
How are you certain that these packets are even processed by Rx? UDP doesn't work with ACK. Make it TCP. At least you will know that these are being processed. Firewalls are rather smart against this rudimentary code.
Is this your own server? If not, you will be in soup.

**Comment by V1L3G0D** [comment]
hahau think im an idiot? i do this everyday and not always in loop i only loop when if testing a few things. you ask alotta questions u know.   bla bla bla udp bla. i know code. nd fyi that is art. i call it, 

~Teh Twin DoS Towers~ 

 NTF starting price $70,000,000
