### ISSUE TITLE
everyone! stop downloading this. this is fake. and it doesn't work on new pythons. you can tell your friends that it is real and scare them but actually it is total fake. and if you are using new python code for new python is in the comments

### ISSUE THREAD

**Issue by XKMR** [Ha3MrX/DDos-Attack#62]
import sys
import os
import time
import socket
import random
#Code Time
#from datetime import datetime
#now = datetime.now()
#hour = now.hour
#minute = now.minute
#day = now.day
#month = now.month
#year = now.year
#print("date: "+year+"/"+month+"/"+day+" | time: "+hour+":"+minute)
os.system("color 8A")
os.system("cls")
print(" ██  ██   ████   ██      ██  ██  ██   ████   ██████")
print(" ██ ██   ██  ██  ████  ████  ██  ██  ██  ██  ██  ██")
print(" ████    ██████  ██████████   ████   ██████  ██████")
print(" ██ ██   ██  ██  ██  ██  ██    ██    ██  ██  ██ ██")
print(" ██  ██  ██  ██  ██      ██    ██    ██  ██  ██  ██")
print
print
##############
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
bytes = random._urandom(1490)
#############

md = input("press Enter to start or s and enter to settings>>> ")
if md == "s" :
 os.system("cls")
 print(" ██  ██   ████   ██      ██  ██  ██   ████   ██████")
 print(" ██ ██   ██  ██  ████  ████  ██  ██  ██  ██  ██  ██")
 print(" ████    ██████  ██████████   ████   ██████  ██████")
 print(" ██ ██   ██  ██  ██  ██  ██    ██    ██  ██  ██ ██")
 print(" ██  ██  ██  ██  ██      ██    ██    ██  ██  ██  ██")
 print
 print
 print("Settings: ")
 print
 print("   color - change cmd color")
 setac = input(" type action: ")
 print
 print
 print("actions: ")
 if setac == "color":
  print("   0 = Black       8 = Gray")
  print("   1 = Blue        9 = Light Blue")
  print("   2 = Green       A = Light Green")
  print("   3 = Aqua        B = Light Aqua")
  print("   4 = Red         C = Light Red")
  print("   5 = Purple      D = Light Purple")
  print("   6 = Yellow      E = Light Yellow")
  print("   7 = White       F = Bright White")
  print
  print("   color code is 2 chars char 1: background color char 2: text color")
  print("   for example: 70 will be Black text with white background")
  print
  print
  clrset = input("   type color>>> ")
  os.system("color "+clrset)
os.system("cls")
print(" ██  ██   ████   ██      ██  ██  ██   ████   ██████")
print(" ██ ██   ██  ██  ████  ████  ██  ██  ██  ██  ██  ██")
print(" ████    ██████  ██████████   ████   ██████  ██████")
print(" ██ ██   ██  ██  ██  ██  ██    ██    ██  ██  ██ ██")
print(" ██  ██  ██  ██  ██      ██    ██    ██  ██  ██  ██")
print
print
ip =   input("   IP Target >>> ")
port = input("   Port      >>> ")
os.system("cls")
print(" ██  ██   ████   ██      ██  ██  ██   ████   ██████")
print(" ██ ██   ██  ██  ████  ████  ██  ██  ██  ██  ██  ██")
print(" ████    ██████  ██████████   ████   ██████  ██████")
print(" ██ ██   ██  ██  ██  ██  ██    ██    ██  ██  ██ ██")
print(" ██  ██  ██  ██  ██      ██    ██    ██  ██  ██  ██")
print
print
print ("[                    ] 0%")
time.sleep(0.5)
os.system("cls")
print(" ██  ██   ████   ██      ██  ██  ██   ████   ██████")
print(" ██ ██   ██  ██  ████  ████  ██  ██  ██  ██  ██  ██")
print(" ████    ██████  ██████████   ████   ██████  ██████")
print(" ██ ██   ██  ██  ██  ██  ██    ██    ██  ██  ██ ██")
print(" ██  ██  ██  ██  ██      ██    ██    ██  ██  ██  ██")
print
print
print ("[=                   ] 1%")
time.sleep(0.5)
os.system("cls")
print(" ██  ██   ████   ██      ██  ██  ██   ████   ██████")
print(" ██ ██   ██  ██  ████  ████  ██  ██  ██  ██  ██  ██")
print(" ████    ██████  ██████████   ████   ██████  ██████")
print(" ██ ██   ██  ██  ██  ██  ██    ██    ██  ██  ██ ██")
print(" ██  ██  ██  ██  ██      ██    ██    ██  ██  ██  ██")
print
print
print ("[==                  ] 5%")
time.sleep(0.5)
os.system("cls")
print(" ██  ██   ████   ██      ██  ██  ██   ████   ██████")
print(" ██ ██   ██  ██  ████  ████  ██  ██  ██  ██  ██  ██")
print(" ████    ██████  ██████████   ████   ██████  ██████")
print(" ██ ██   ██  ██  ██  ██  ██    ██    ██  ██  ██ ██")
print(" ██  ██  ██  ██  ██      ██    ██    ██  ██  ██  ██")
print
print
print ("[====                 ] 10%")
time.sleep(0.5)
os.system("cls")
print(" ██  ██   ████   ██      ██  ██  ██   ████   ██████")
print(" ██ ██   ██  ██  ████  ████  ██  ██  ██  ██  ██  ██")
print(" ████    ██████  ██████████   ████   ██████  ██████")
print(" ██ ██   ██  ██  ██  ██  ██    ██    ██  ██  ██ ██")
print(" ██  ██  ██  ██  ██      ██    ██    ██  ██  ██  ██")
print
print
print ("[===========          ] 50%")
time.sleep(0.5)
os.system("cls")
print(" ██  ██   ████   ██      ██  ██  ██   ████   ██████")
print(" ██ ██   ██  ██  ████  ████  ██  ██  ██  ██  ██  ██")
print(" ████    ██████  ██████████   ████   ██████  ██████")
print(" ██ ██   ██  ██  ██  ██  ██    ██    ██  ██  ██ ██")
print(" ██  ██  ██  ██  ██      ██    ██    ██  ██  ██  ██")
print
print
print ("[===============      ] 70%")
time.sleep(0.5)
os.system("cls")
print(" ██  ██   ████   ██      ██  ██  ██   ████   ██████")
print(" ██ ██   ██  ██  ████  ████  ██  ██  ██  ██  ██  ██")
print(" ████    ██████  ██████████   ████   ██████  ██████")
print(" ██ ██   ██  ██  ██  ██  ██    ██    ██  ██  ██ ██")
print(" ██  ██  ██  ██  ██      ██    ██    ██  ██  ██  ██")
print
print
print ("[==================   ] 80%")
time.sleep(0.5)
os.system("cls")
print(" ██  ██   ████   ██      ██  ██  ██   ████   ██████")
print(" ██ ██   ██  ██  ████  ████  ██  ██  ██  ██  ██  ██")
print(" ████    ██████  ██████████   ████   ██████  ██████")
print(" ██ ██   ██  ██  ██  ██  ██    ██    ██  ██  ██ ██")
print(" ██  ██  ██  ██  ██      ██    ██    ██  ██  ██  ██")
print
print
print ("[=====================] 100%")
time.sleep(0.3)
os.system("cls")
print("loading.")
print("starting DDoS")
time.sleep(0.3)
os.system("cls")
print("loading..")
print("starting DDoS")
time.sleep(0.3)
os.system("cls")
print("loading...")
print("starting DDoS")
time.sleep(0.3)
os.system("cls")
print("loading....")
print("starting DDoS")
time.sleep(0.3)
os.system("cls")
print("loading.....")
print("starting DDoS")
time.sleep(0.3)
os.system("cls")
print("loading......")
print("Connecting to DDoS server")
time.sleep(0.3)
os.system("cls")
print("loading.......")
print("Connecting to DDoS server")
time.sleep(0.3)
os.system("cls")
print("loading........")
print("Connecting to DDoS server")
time.sleep(0.3)
os.system("cls")
print("loading.")
print("Connecting to DDoS server")
time.sleep(0.3)
os.system("cls")
print("loading..")
print("Connecting to DDoS server")
time.sleep(0.3)
print("Connected")
time.sleep(2)
os.system("cls")
print("loading...")
print("sending ip:port to the server")
time.sleep(0.3)
os.system("cls")
print("loading....")
print("sending ip:port to the server")
time.sleep(0.3)
os.system("cls")
print("loading.....")
print("sending ip:port to the server")
time.sleep(0.3)
os.system("cls")
print("loading......")
print("sending ip:port to the server")
time.sleep(0.3)
os.system("cls")
print("loading.......")
print("sending ip:port to the server")
time.sleep(0.3)
os.system("cls")
print("loading........")
print("sending ip:port to the server")
time.sleep(0.3)
os.system("cls")
print("loading.")
print("sending ip:port to the server")
print("sent and comfirmed by server")
time.sleep(2)
os.system("cls")
print("loading..")
print("waiting for server to start the attack")
time.sleep(0.3)
os.system("cls")
print("loading...")
print("waiting for server to start the attack")
time.sleep(0.3)
os.system("cls")
print("loading....")
print("waiting for server to start the attack")
time.sleep(0.3)
os.system("cls")
print("loading.....")
print("waiting for server to start the attack")
time.sleep(0.3)
os.system("cls")
print("loading......")
print("waiting for server to start the attack")
time.sleep(0.3)
os.system("cls")
print("loading.......")
print("waiting for server to start the attack")
print("server started the attack")
time.sleep(2)
os.system("cls")
print("loading........")
print("comfirming details")
time.sleep(0.3)
os.system("cls")
print("loading.")
print("comfirming details")
time.sleep(0.3)
os.system("cls")
print("loading..")
print("comfirming details")
time.sleep(0.3)
os.system("cls")
print("loading...")
print("comfirming details")
time.sleep(0.3)
os.system("cls")
print("loading....")
print("comfirming details")
time.sleep(0.3)
os.system("cls")
print("loading.....")
print("comfirming details")
time.sleep(0.3)
os.system("cls")
print("loading......")
print("comfirming details")
time.sleep(0.3)
os.system("cls")
print("loading.......")
print("comfirming details")
time.sleep(0.3)
os.system("cls")
print("loading........")
print("comfirming details")
print("comfirmed")
time.sleep(2)
os.system("cls")
print(" ██  ██   ████   ██      ██  ██  ██   ████   ██████")
print(" ██ ██   ██  ██  ████  ████  ██  ██  ██  ██  ██  ██")
print(" ████    ██████  ██████████   ████   ██████  ██████")
print(" ██ ██   ██  ██  ██  ██  ██    ██    ██  ██  ██ ██")
print(" ██  ██  ██  ██  ██      ██    ██    ██  ██  ██  ██")
print
print
print(ip+" is now being attacked by you! form port "+port)
time.sleep(0.2)
stop = input("to stop attack type stop >>> ")
if stop == "stop":
 os.system("cls")
 print("sending stop command to the server...")
 time.sleep(3)
 input("attack ended. to exit press enter")
 exit()
else:
 input("command <"+stop+"> is not defind. attack is still on, to exit press: Enter")

**Comment by V1L3G0D** [comment]
Lolllll @XKMR  bruh you serious?  Its made to work with perfectly with python 2.6 obviously if you dont know how to loop your connection into localhost then you might wanna sell your phone and go get you a ddr2 maybe a amd x2 dirt cheap loop it and watch. There are some changes in the past month but nothing that someone who can read basic script cant fix on there own. Litterally. Can we revoke thia guys github comment priv 😂   
Quick preview.


![16330779856315202115120462937791](https://user-images.githubusercontent.com/86334187/135592807-bcf93aca-6389-45da-8842-621a0b8f0259.jpg)


Next time u wanna comment. Just Donut. 🍩

**Comment by XKMR** [comment]
everyone calm down.
the attack that @Ha3MrX made is not even dangerous. it just send a few bites like a normal ping so I don't count that as a DDoS attack

**Comment by natethemaker** [comment]
https://github.com/H1R0GH057/Anonymous
